//
// Created by Dor Shukrun on 23/08/2024.
//

#ifndef STARWARSSIMULATION_SIMULATIONMODEL_H
#define STARWARSSIMULATION_SIMULATIONMODEL_H


class SimulationModel {

};


#endif //STARWARSSIMULATION_SIMULATIONMODEL_H
